spring:
  redis:
    host: 127.0.0.1
    port: 6379
  mail:
    host: smtp.163.com
    username: 17695920199@163.com
    password: 920618dy.
    enable:  true
    smtp:
      auth: true
    starttls:
      enable: true
      required: true
  datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/office2
        username: root
        password: 1234
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false    
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: LEGACYHTML5  
 ##  mvc:
  ##   static-path-pattern: /image/**
 ##  resources:
  ##   static-locations: file:D//picture/
    
server:
  port: 82

local:
  resource: http://127.0.0.1:81/courseTea/

file:
  path: d:/coin/office/
  
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  config-locations: classpath:mybatis/config.xml
  type-aliases-package: com.office.entity  # 注意：对应实体类的路径
